import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.cbook import boxplot_stats

data = pd.read_csv("iris.csv")
print(data.head())
print("\n------------------------------------------------------------------------")
print(data.describe())
print("\n------------------------------------------------------------------------")
print(data.isnull().sum())
print("\n------------------------------------------------------------------------")
print(data.info())
print("\n------------------------------------------------------------------------")
sns.histplot(x=data['SepalLengthCm'], kde=True)
plt.show()
sns.histplot(x=data['SepalWidthCm'], kde=True)
plt.show()
sns.histplot(x=data['PetalLengthCm'], kde=True)
plt.show()
sns.histplot(x=data['PetalWidthCm'], kde=True)
plt.show()
sns.boxplot(data['SepalLengthCm'])
plt.show()
sns.boxplot(data['SepalWidthCm'])
plt.show()
sns.boxplot(data['PetalLengthCm'])
plt.show()
sns.boxplot(data['PetalWidthCm'])
plt.show()
print("---------------------------------------------------------------------------")
stats = boxplot_stats(data['SepalWidthCm'])
print(stats)
print("---------------------------------------------------------------------------")
outliers = stats[0].get("fliers")
print(outliers)
