import pandas as pd

df = pd.read_csv("iris.csv")
print(df.head())
print("\n------------------------------------------------------------------------")
print(df.describe(()))
print("\n------------------------------------------------------------------------")
print(df.info())
print("\n------------------------------------------------------------------------")
print("Mean: \n")
# print(df.mean()) # deprecation error
print(df.mean(numeric_only=True))
print("\n------------------------------------------------------------------------")
print("Median: \n")
print(df.median(numeric_only=True))
print("\n------------------------------------------------------------------------")
print("Species Mode: \n")
print(df['Species'].mode())
print("\n------------------------------------------------------------------------")
print(df.groupby(['Species']).count())
print("\n------------------------------------------------------------------------")
print("Standard deviation: ")
print(df.SepalLengthCm.std())
print(df.SepalWidthCm.std())
print(df.PetalLengthCm.std())
print(df.PetalWidthCm.std())
print("\n------------------------------------------------------------------------")
print("Iris-setosa")
setosa = df['Species'] == 'Iris-setosa'
print(df[setosa].describe())
print("\n-------------------------------------------------------------------------")
print("Iris-versicolor")
versicolor = df['Species'] == 'Iris-versicolor'
print(df[versicolor].describe())
print("\n-------------------------------------------------------------------------")
print("Iris-virginica")
virginica = df['Species'] == 'Iris-virginica'
print(df[virginica].describe())
print("\n-------------------------------------------------------------------------")
